---
sudo: false
language: ruby
cache: bundler
before_install:
  - gem install bundler -v 1.17.2
bundler_args: --jobs=3 --retry=3 --without documentation
script: bin/ci
rvm:
  - 2.5.3
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
